# Generated by Django 4.2.1 on 2023-06-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_leetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leetcode',
            name='end_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leetcode',
            name='start_time',
            field=models.CharField(max_length=50),
        ),
    ]
