# Generated by Django 4.2.1 on 2023-06-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_leetcode_end_time_alter_leetcode_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leetcode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
