# Generated by Django 4.2.1 on 2023-06-03 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_leetcode_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='type',
        ),
    ]
