# Generated by Django 4.2.1 on 2023-06-03 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_company_added_date_remove_company_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
    ]
