# Generated by Django 4.2.1 on 2023-06-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_employee_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('duration', models.IntegerField()),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=255)),
                ('in_24_hours', models.BooleanField()),
            ],
        ),
    ]
