# Generated by Django 4.2.2 on 2023-06-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_allcontests_codingplatform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackerrank',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
