# Generated by Django 4.2.2 on 2023-06-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_hackerrank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackerrank',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
