# Generated by Django 4.2.2 on 2023-06-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_hackerrank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackerearth',
            name='type',
            field=models.TextField(default='contest'),
        ),
    ]
